dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp35-cp35m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install https://download.pytorch.org/whl/cpu/torch-1.0.0-cp37-cp37m-linux_x86_64.whl; fi
install: python setup.py install
script: pytest
